### ISSUE TITLE
Maintainance of allmychanges.com

### ISSUE THREAD

**Issue by williamdes** [code-lts/welcome#5]
Hello @svetlyak40wt 

The project is not accessible and seems unmaintained.
I love the idea and want the project to continue, how can I help you ?

https://allmychanges.com/

**Comment by svetlyak40wt** [comment]
Hi, @williamdes!

Nowadays I have no time and will to support allmychanges.com :(

The main reason is that I'm not interested in maintaining my Python code anymore because of the switch to the Common Lisp. If you'll be able to find a few people who will want to maintain this project, I might establish an organization and to opensource the code behind the Allmychanges.com.

**Comment by williamdes** [comment]
Hi @svetlyak40wt!
I want to maintain the project, if you want to transfer repositories you can transfer them here 
I want to maintain the project and possibly rewrite the python code

I need this project to be running and can host it on my server 

I will invite you to this organization, I am ready to get the project back and running!

**Comment by williamdes** [comment]
Hi @svetlyak40wt 

Do you have some news to share or some progress ?

**Comment by svetlyak40wt** [comment]
Hi, @williamdes!

Excuse me for the delay.

I'd prefer to opensource the code in the separate https://github.com/allmychanges organization.
Also, I can give you access to the server where the project is deployed so that you'll be able to fix it and deploy new versions.

What do you think about this?

**Comment by williamdes** [comment]
Hi! 
No worries I understand

Sure, could you move the client repo from your account into the organization? 

Also, am I responsible of the project or do you want to validate pull requests?

**Comment by svetlyak40wt** [comment]
I can help you to figure out what is going on in the codebase but will not be available to review all pull-request.

If you'll need some help, make a pull-request and invite me to review.

It would be nice also if you'll be able to attract other contributors. 

I spend a lot of time working on this project and will be happy to see it alive again! :)

**Comment by williamdes** [comment]
Okay, thank you!
I will try to find contributors to help me

Disclaimer: I did not have a look to tee code for now

Would you accept that some parts be re-written in another language it is an option

Or is the maintenance idea is only to maintain the project afloat and maybe speed some parts?

Is the server dedicated for the project?

**Comment by svetlyak40wt** [comment]
I'd prefer the backend to remain written in Python. But it needs to be ported to Python3.

Under maintenance, I also mean a new feature development.

The last feature I started to implement is projects moderators. It should solve the problem when a project's parsing broke and somebody (who cares about it) have to fix some settings.

This is important because changelog file or site formats are constantly changed on the internet and sometimes it is impossible to make a parser to automatically understand these changes. And it is very time-consuming for one man to take care of dozens of broken projects. That is why I thought it would be nice to have a help of community here.

**Comment by williamdes** [comment]
Okay, this is pretty clear
I will have to understand python but this will be a good exercise
Can you describe the infrastructure?
CDN?
How hosts the DNS?
How works the HTTPS?

I will need all those small details to have a clear view of any impacts while learning about the project

**Comment by williamdes** [comment]
Can you bring back up the website ?
If you need to email-me some credentials: williamdes@wdes.fr
